# Update your Quarkus project to a newer version

name: quarkus-update-action
on:
  schedule:
  - cron: '0 0 * * 3'
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repository using working-copy as its path
      uses: actions/checkout@v2
      with:
        path: working-copy

    - name: Update Quarkus version
      uses: jthambly/update-quarkus@v1.0.10
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        checklist: |
          |
          Migration Checklist:
         
          - [x] Reviewers and Assignees assigned
          - [x] Link to Migration Documentation provided
          - [ ] Migration Documentation reviewed
          - [ ] Changes reviewed against existing project
          - [ ] File modifications reviewed
          - [ ] Automated checks performed
          - [ ] Manual QA performed